import { Body, Controller, Get, Param, Post, Query, Req } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { z } from "zod";
import { AuthService } from "../auth/auth.service";
import { DatabaseService } from "../database/database.service";
import { AuditService } from "../audit/audit.service";
const scoreSchema=z.object({semesterId:z.string().uuid(),indicatorId:z.string().uuid(),scaleOptionId:z.string().uuid()});
@Controller("assessment") export class AssessmentController {
 constructor(private readonly auth:AuthService,private readonly db:DatabaseService,private readonly audit:AuditService){}
 @Post("frameworks/default") async bootstrap(@Req() req:FastifyRequest){const a=this.auth.require(req,["SCHOOL_ADMIN"]);return this.db.transaction(async c=>{const existing=await c.query("SELECT id FROM assessment_frameworks WHERE is_active LIMIT 1");if(existing.rowCount)return {id:existing.rows[0].id,created:false};const scale=(await c.query("INSERT INTO assessment_scales(school_id,name) VALUES($1,'Perkembangan Default') RETURNING id",[a.schoolId])).rows[0];const options=[];for(const [i,code] of ["BB","MB","BSH","BSB"].entries())options.push((await c.query("INSERT INTO assessment_scale_options(school_id,scale_id,code,label,position) VALUES($1,$2,$3,$3,$4) RETURNING *",[a.schoolId,scale.id,code,i+1])).rows[0]);const framework=(await c.query("INSERT INTO assessment_frameworks(school_id,scale_id,name) VALUES($1,$2,'Kurikulum PAUD') RETURNING id",[a.schoolId,scale.id])).rows[0];for(const [i,name] of ["Nilai Agama dan Moral","Fisik Motorik","Kognitif","Bahasa","Sosial Emosional","Seni"].entries()){const area=(await c.query("INSERT INTO development_areas(school_id,framework_id,name,position) VALUES($1,$2,$3,$4) RETURNING id",[a.schoolId,framework.id,name,i+1])).rows[0];const sub=(await c.query("INSERT INTO sub_areas(school_id,development_area_id,name,position) VALUES($1,$2,'Perkembangan',1) RETURNING id",[a.schoolId,area.id])).rows[0];await c.query("INSERT INTO indicators(school_id,sub_area_id,description,position) VALUES($1,$2,$3,1)",[a.schoolId,sub.id,`Observasi ${name}`]);}await this.audit.record({schoolId:a.schoolId,actorUserId:a.userId,action:"assessment_framework.created",entityType:"assessment_framework",entityId:framework.id},c);return {id:framework.id,created:true};},a.schoolId)}
 @Get("students/:studentId") async workspace(@Req() req:FastifyRequest,@Param("studentId") studentId:string,@Query("semesterId") semesterId:string){const a=this.auth.require(req,["SCHOOL_ADMIN","TEACHER"]);return this.db.transaction(async c=>{const student=(await c.query("SELECT id,name FROM students WHERE id=$1",[studentId])).rows[0];if(!student)return null;const scales=(await c.query("SELECT o.id,o.code,o.label,o.position FROM assessment_scale_options o JOIN assessment_frameworks f ON f.scale_id=o.scale_id WHERE f.is_active ORDER BY o.position")).rows;const indicators=(await c.query(`SELECT da.id AS area_id,da.name AS area_name,i.id,i.description,sa.name AS sub_area_name,ass.scale_option_id FROM indicators i JOIN sub_areas sa ON sa.id=i.sub_area_id JOIN development_areas da ON da.id=sa.development_area_id JOIN assessment_frameworks f ON f.id=da.framework_id LEFT JOIN student_assessments ass ON ass.indicator_id=i.id AND ass.student_id=$1 AND ass.semester_id=$2 WHERE f.is_active ORDER BY da.position,sa.position,i.position`,[studentId,semesterId])).rows;return {student,scales,indicators};},a.schoolId)}
 @Post("students/:studentId") async save(@Req() req:FastifyRequest,@Param("studentId") studentId:string,@Body() body:unknown){const a=this.auth.require(req,["SCHOOL_ADMIN","TEACHER"]);const x=scoreSchema.parse(body);return this.db.transaction(async c=>{const valid=await c.query("SELECT 1 FROM students s JOIN semesters sem ON sem.id=$2 WHERE s.id=$1",[studentId,x.semesterId]);if(!valid.rowCount)throw new Error("Siswa atau semester tidak ditemukan");const r=await c.query(`INSERT INTO student_assessments(school_id,student_id,semester_id,indicator_id,scale_option_id,assessed_by) SELECT $1,$2,$3,$4,$5,$6 WHERE EXISTS(SELECT 1 FROM indicators WHERE id=$4) AND EXISTS(SELECT 1 FROM assessment_scale_options WHERE id=$5) ON CONFLICT(student_id,semester_id,indicator_id) DO UPDATE SET scale_option_id=EXCLUDED.scale_option_id,assessed_by=EXCLUDED.assessed_by,assessed_at=now() RETURNING *`,[a.schoolId,studentId,x.semesterId,x.indicatorId,x.scaleOptionId,a.userId]);if(!r.rowCount)throw new Error("Indikator atau skala tidak ditemukan");await this.audit.record({schoolId:a.schoolId,actorUserId:a.userId,action:"student_assessment.saved",entityType:"student_assessment",entityId:r.rows[0].id},c);return r.rows[0];},a.schoolId)} }
