import { Body, Controller, Get, Param, Post, Put, Query, Req } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { createHash, randomBytes, randomInt } from "crypto";
import { z } from "zod";
import { DEFAULT_TK_TEMPLATE_NAME } from "../assessment/default-tk-template";
import { AuthService } from "../auth/auth.service";
import { DatabaseService } from "../database/database.service";
import { AuditService } from "../audit/audit.service";
import { ReportPdfService } from "../files/report-pdf.service";

const transition = z.object({ action: z.enum(["submit", "review", "revision", "approve"]), note: z.string().max(1000).optional() });
const reportAssessment = z.object({ scaleOptionId: z.string().uuid() });

@Controller("reports")
export class ReportsController {
  constructor(private readonly auth: AuthService, private readonly db: DatabaseService, private readonly audit: AuditService, private readonly pdf: ReportPdfService) {}

  @Get("progress")
  async progress(@Req() request: FastifyRequest, @Query("semesterId") semesterId: string) { const actor = this.auth.require(request); return this.db.transaction(async (client) => (await client.query("SELECT s.id,s.name,rep.id AS report_id,rep.status FROM students s LEFT JOIN reports rep ON rep.student_id=s.id AND rep.semester_id=$1 ORDER BY s.name", [semesterId])).rows, actor.schoolId); }

  @Get("review-queue")
  async reviewQueue(@Req() request: FastifyRequest) { const actor = this.auth.require(request, ["SCHOOL_ADMIN", "PRINCIPAL"]); return this.db.transaction(async (client) => (await client.query("SELECT r.id,r.status,r.submitted_at,s.name AS student_name,sem.name AS semester_name FROM reports r JOIN students s ON s.id=r.student_id JOIN semesters sem ON sem.id=r.semester_id WHERE r.status IN ('SUBMITTED','IN_REVIEW','REVISION_REQUIRED','APPROVED') ORDER BY r.submitted_at NULLS LAST,r.updated_at DESC")).rows, actor.schoolId); }

  @Post("students/:studentId/draft")
  async draft(@Req() request: FastifyRequest, @Param("studentId") studentId: string, @Body() body: unknown) { const actor = this.auth.require(request, ["SCHOOL_ADMIN", "TEACHER"]); const input = z.object({ semesterId: z.string().uuid() }).parse(body); return this.db.transaction(async (client) => { const result = await client.query("INSERT INTO reports(school_id,student_id,semester_id) SELECT $1,$2,$3 WHERE EXISTS(SELECT 1 FROM students WHERE id=$2) AND EXISTS(SELECT 1 FROM semesters WHERE id=$3) ON CONFLICT(student_id,semester_id) DO UPDATE SET updated_at=now() RETURNING *", [actor.schoolId, studentId, input.semesterId]); if (!result.rowCount) throw new Error("Siswa atau semester tidak ditemukan"); await this.audit.record({ schoolId: actor.schoolId, actorUserId: actor.userId, action: "report.draft_created", entityType: "report", entityId: result.rows[0].id }, client); return result.rows[0]; }, actor.schoolId); }

  @Put(":id/assessments/:indicatorId")
  async saveAssessment(@Req() request: FastifyRequest, @Param("id") id: string, @Param("indicatorId") indicatorId: string, @Body() body: unknown) { const actor = this.auth.require(request, ["SCHOOL_ADMIN", "TEACHER"]); const input = reportAssessment.parse(body); return this.db.transaction(async (client) => { const report = (await client.query<{ student_id: string; semester_id: string; status: string }>("SELECT student_id,semester_id,status FROM reports WHERE id=$1", [id])).rows[0]; if (!report) throw new Error("Rapor tidak ditemukan"); if (!["DRAFT", "REVISION_REQUIRED"].includes(report.status)) throw new Error("Rapor tidak dapat diubah pada status saat ini"); const valid = await client.query(`SELECT 1 FROM indicators i JOIN sub_areas sa ON sa.id=i.sub_area_id JOIN development_areas da ON da.id=sa.development_area_id JOIN assessment_frameworks f ON f.id=da.framework_id JOIN assessment_scale_options o ON o.scale_id=f.scale_id WHERE i.id=$1 AND o.id=$2 AND f.name=$3 AND f.is_active`, [indicatorId, input.scaleOptionId, DEFAULT_TK_TEMPLATE_NAME]); if (!valid.rowCount) throw new Error("Indikator atau skala tidak valid"); const saved = (await client.query(`INSERT INTO student_assessments(school_id,student_id,semester_id,indicator_id,scale_option_id,assessed_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(student_id,semester_id,indicator_id) DO UPDATE SET scale_option_id=EXCLUDED.scale_option_id,assessed_by=EXCLUDED.assessed_by,assessed_at=now() RETURNING *`, [actor.schoolId, report.student_id, report.semester_id, indicatorId, input.scaleOptionId, actor.userId])).rows[0]; await this.audit.record({ schoolId: actor.schoolId, actorUserId: actor.userId, action: "report_assessment.saved", entityType: "student_assessment", entityId: saved.id, metadata: { reportId: id } }, client); return saved; }, actor.schoolId); }

  @Post(":id/transition")
  async move(@Req() request: FastifyRequest, @Param("id") id: string, @Body() body: unknown) { const actor = this.auth.require(request); const input = transition.parse(body); return this.db.transaction(async (client) => { const report = (await client.query<{ status: string }>("SELECT status FROM reports WHERE id=$1", [id])).rows[0]; if (!report) throw new Error("Rapor tidak ditemukan"); const rules: Record<string, [string, string[]]> = { submit: ["SUBMITTED", ["DRAFT"]], review: ["IN_REVIEW", ["SUBMITTED"]], revision: ["REVISION_REQUIRED", ["IN_REVIEW"]], approve: ["APPROVED", ["IN_REVIEW"]] }; const [to, from] = rules[input.action]; if (!from.includes(report.status)) throw new Error("Perubahan status tidak valid"); if (input.action === "submit" && !( ["SCHOOL_ADMIN", "TEACHER"] as string[]).includes(actor.role)) throw new Error("Akses ditolak"); if (["review", "revision", "approve"].includes(input.action) && !( ["SCHOOL_ADMIN", "PRINCIPAL"] as string[]).includes(actor.role)) throw new Error("Akses ditolak"); const updated = (await client.query("UPDATE reports SET status=$1,submitted_at=CASE WHEN $1='SUBMITTED' THEN now() ELSE submitted_at END,approved_at=CASE WHEN $1='APPROVED' THEN now() ELSE approved_at END,updated_at=now() WHERE id=$2 RETURNING *", [to, id])).rows[0]; await this.audit.record({ schoolId: actor.schoolId, actorUserId: actor.userId, action: `report.${input.action}`, entityType: "report", entityId: id }, client); return updated; }, actor.schoolId); }

  @Post(":id/publish")
  async publish(@Req() request: FastifyRequest, @Param("id") id: string) {
    const actor = this.auth.require(request, ["SCHOOL_ADMIN", "PRINCIPAL"]);
    return this.db.transaction(async (client) => {
      const report = (await client.query<any>(`SELECT r.*,s.name AS student_name,s.nickname,s.student_number,s.birth_date,s.birth_place,s.gender,s.religion,s.child_order,s.address,c.name AS class_name,sem.name AS semester_name,ay.name AS academic_year_name FROM reports r JOIN students s ON s.id=r.student_id LEFT JOIN classes c ON c.id=s.class_id JOIN semesters sem ON sem.id=r.semester_id JOIN academic_years ay ON ay.id=sem.academic_year_id WHERE r.id=$1 FOR UPDATE`, [id])).rows[0];
      if (!report) throw new Error("Rapor tidak ditemukan"); if (report.status !== "APPROVED") throw new Error("Hanya rapor yang disetujui dapat diterbitkan");
      const assessmentRows = (await client.query<any>(`SELECT da.name AS area_name,da.position AS area_position,sa.name AS sub_area_name,sa.position AS sub_area_position,i.description,i.position,opt.code FROM student_assessments assessment JOIN indicators i ON i.id=assessment.indicator_id JOIN sub_areas sa ON sa.id=i.sub_area_id JOIN development_areas da ON da.id=sa.development_area_id JOIN assessment_frameworks f ON f.id=da.framework_id JOIN assessment_scale_options opt ON opt.id=assessment.scale_option_id WHERE assessment.student_id=$1 AND assessment.semester_id=$2 AND f.name=$3 AND f.is_active ORDER BY da.position,sa.position,i.position`, [report.student_id, report.semester_id, DEFAULT_TK_TEMPLATE_NAME])).rows;
      const narratives = (await client.query<any>(`SELECT da.name,rn.content FROM report_narratives rn JOIN development_areas da ON da.id=rn.development_area_id JOIN assessment_frameworks f ON f.id=da.framework_id WHERE rn.report_id=$1 AND f.name=$2 AND f.is_active ORDER BY da.position`, [id, DEFAULT_TK_TEMPLATE_NAME])).rows;
      const growth = (await client.query("SELECT weight_kg,height_cm,head_circumference_cm FROM growth_records WHERE student_id=$1 AND semester_id=$2", [report.student_id, report.semester_id])).rows[0] ?? null;
      const attendance = (await client.query("SELECT sick_days,permission_days,unexcused_days FROM attendance_summaries WHERE student_id=$1 AND semester_id=$2", [report.student_id, report.semester_id])).rows[0] ?? null;
      const guardians = (await client.query("SELECT name,relationship,phone,occupation,is_primary FROM guardian_contacts WHERE student_id=$1 ORDER BY is_primary DESC,name", [report.student_id])).rows;
      const snapshot = { report: { id: report.id, status: report.status }, student: { name: report.student_name, nickname: report.nickname, student_number: report.student_number, birth_date: report.birth_date, birth_place: report.birth_place, gender: report.gender, religion: report.religion, child_order: report.child_order, address: report.address, class_name: report.class_name }, semester: { name: report.semester_name, academic_year_name: report.academic_year_name }, assessments: assessmentRows, narratives, growth, attendance, guardians };
      const versionNumber = (await client.query<{ next: number }>("SELECT COALESCE(max(version_number),0)+1 AS next FROM report_versions WHERE report_id=$1", [id])).rows[0].next;
      const pdfStorageKey = await this.pdf.storePublishedReport({ schoolId: actor.schoolId, reportId: id, versionNumber, snapshot });
      const version = (await client.query("INSERT INTO report_versions(school_id,report_id,version_number,snapshot,pdf_storage_key,published_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *", [actor.schoolId, id, versionNumber, snapshot, pdfStorageKey, actor.userId])).rows[0];
      const token = randomBytes(32).toString("base64url"), pin = randomInt(0, 1_000_000).toString().padStart(6, "0");
      await client.query("INSERT INTO report_access(school_id,report_version_id,token_hash,pin_hash) VALUES($1,$2,$3,$4)", [actor.schoolId, version.id, createHash("sha256").update(token).digest("hex"), createHash("sha256").update(pin).digest("hex")]);
      const deliveries = await client.query("INSERT INTO report_deliveries(school_id,report_version_id,guardian_contact_id,recipient_phone) SELECT $1,$2,g.id,g.phone FROM guardian_contacts g WHERE g.school_id=$1 AND g.student_id=$3 RETURNING id", [actor.schoolId, version.id, report.student_id]);
      await client.query("UPDATE reports SET status='PUBLISHED',updated_at=now() WHERE id=$1", [id]);
      await this.audit.record({ schoolId: actor.schoolId, actorUserId: actor.userId, action: "report.published", entityType: "report_version", entityId: version.id, metadata: { pdfStorageKey } }, client);
      return { ...version, parentAccess: { link: `/r/${token}`, pin }, deliveryCount: deliveries.rowCount };
    }, actor.schoolId);
  }

  @Get(":id/editor")
  async editor(@Req() request: FastifyRequest, @Param("id") id: string) { const actor = this.auth.require(request, ["SCHOOL_ADMIN", "TEACHER"]); return this.db.transaction(async (client) => { const report = (await client.query("SELECT r.*,s.name AS student_name,s.student_number,sem.name AS semester_name FROM reports r JOIN students s ON s.id=r.student_id JOIN semesters sem ON sem.id=r.semester_id WHERE r.id=$1", [id])).rows[0]; if (!report) return null; const areas = (await client.query(`SELECT da.id,da.name,count(i.id)::int AS indicator_count,count(assessment.id)::int AS assessed_count,n.content AS narrative FROM development_areas da JOIN assessment_frameworks f ON f.id=da.framework_id JOIN sub_areas sub ON sub.development_area_id=da.id JOIN indicators i ON i.sub_area_id=sub.id LEFT JOIN student_assessments assessment ON assessment.indicator_id=i.id AND assessment.student_id=$1 AND assessment.semester_id=$2 LEFT JOIN report_narratives n ON n.report_id=$3 AND n.development_area_id=da.id WHERE f.name=$4 AND f.is_active GROUP BY da.id,da.name,n.content,da.position ORDER BY da.position`, [report.student_id, report.semester_id, id, DEFAULT_TK_TEMPLATE_NAME])).rows; const assessments = (await client.query(`SELECT da.id AS area_id,sub.name AS sub_area_name,i.description,opt.code AS scale_code FROM indicators i JOIN sub_areas sub ON sub.id=i.sub_area_id JOIN development_areas da ON da.id=sub.development_area_id JOIN assessment_frameworks f ON f.id=da.framework_id LEFT JOIN student_assessments sa ON sa.indicator_id=i.id AND sa.student_id=$1 AND sa.semester_id=$2 LEFT JOIN assessment_scale_options opt ON opt.id=sa.scale_option_id WHERE f.name=$3 AND f.is_active ORDER BY da.position,sub.position,i.position`, [report.student_id, report.semester_id, DEFAULT_TK_TEMPLATE_NAME])).rows; const growth = (await client.query("SELECT weight_kg,height_cm,head_circumference_cm FROM growth_records WHERE student_id=$1 AND semester_id=$2", [report.student_id, report.semester_id])).rows[0] ?? null; const attendance = (await client.query("SELECT sick_days,permission_days,unexcused_days FROM attendance_summaries WHERE student_id=$1 AND semester_id=$2", [report.student_id, report.semester_id])).rows[0] ?? null; return { report, areas, assessments, growth, attendance }; }, actor.schoolId); }

  @Put(":id/narratives/:areaId")
  async narrative(@Req() request: FastifyRequest, @Param("id") id: string, @Param("areaId") areaId: string, @Body() body: unknown) { const actor = this.auth.require(request, ["SCHOOL_ADMIN", "TEACHER"]); const input = z.object({ content: z.string().min(1).max(5000) }).parse(body); return this.db.transaction(async (client) => { const report = await client.query("SELECT id,status FROM reports WHERE id=$1", [id]); if (!report.rowCount) throw new Error("Rapor tidak ditemukan"); if (report.rows[0].status === "PUBLISHED") throw new Error("Rapor terbit tidak dapat diubah"); const saved = (await client.query("INSERT INTO report_narratives(school_id,report_id,development_area_id,content,updated_by) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM development_areas WHERE id=$3) ON CONFLICT(report_id,development_area_id) DO UPDATE SET content=EXCLUDED.content,updated_by=EXCLUDED.updated_by,updated_at=now() RETURNING *", [actor.schoolId, id, areaId, input.content, actor.userId])).rows[0]; if (!saved) throw new Error("Area perkembangan tidak ditemukan"); await this.audit.record({ schoolId: actor.schoolId, actorUserId: actor.userId, action: "report_narrative.saved", entityType: "report_narrative", entityId: saved.id }, client); return saved; }, actor.schoolId); }
}
