import { Body, ConflictException, Controller, Get, NotFoundException, Param, Patch, Post, Req } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { z } from "zod";
import { AuditService } from "../audit/audit.service";
import { AuthService } from "../auth/auth.service";
import { DatabaseService } from "../database/database.service";

const staffSchema = z.object({ name: z.string().trim().min(2).max(120), email: z.string().email(), role: z.enum(["TEACHER", "PRINCIPAL"]), password: z.string().min(8).max(128) });
const updateSchema = z.object({ isActive: z.boolean().optional(), password: z.string().min(8).max(128).optional() }).refine(value => value.isActive !== undefined || value.password !== undefined);
const assignmentSchema = z.object({ teacherUserId: z.string().uuid() });

@Controller("staff")
export class StaffController {
  constructor(private readonly auth: AuthService, private readonly db: DatabaseService, private readonly audit: AuditService) {}
  @Get() list(@Req() request: FastifyRequest) { const actor=this.auth.require(request,["SCHOOL_ADMIN"]); return this.db.transaction(async c=>(await c.query("SELECT user_account.id,user_account.name,user_account.email,membership.role,membership.is_active,membership.deactivated_at FROM school_memberships membership JOIN users user_account ON user_account.id=membership.user_id WHERE membership.school_id=$1 ORDER BY membership.role,user_account.name",[actor.schoolId])).rows,actor.schoolId); }
  @Post() async create(@Req() request: FastifyRequest,@Body() body:unknown) { const actor=this.auth.require(request,["SCHOOL_ADMIN"]);const input=staffSchema.parse(body);return this.db.transaction(async c=>{const exists=await c.query("SELECT 1 FROM users WHERE lower(email)=lower($1)",[input.email]);if(exists.rowCount)throw new ConflictException("Email tersebut sudah digunakan.");const user=(await c.query("INSERT INTO users(name,email,password_hash) VALUES($1,lower($2),$3) RETURNING id,name,email",[input.name,input.email,await this.auth.hashPassword(input.password)])).rows[0];await c.query("INSERT INTO school_memberships(user_id,school_id,role) VALUES($1,$2,$3)",[user.id,actor.schoolId,input.role]);await this.audit.record({schoolId:actor.schoolId,actorUserId:actor.userId,action:"staff.created",entityType:"user",entityId:user.id,metadata:{role:input.role}},c);return {...user,role:input.role,is_active:true};},actor.schoolId); }
  @Patch(":userId") async update(@Req() request:FastifyRequest,@Param("userId") userId:string,@Body() body:unknown) { const actor=this.auth.require(request,["SCHOOL_ADMIN"]);const input=updateSchema.parse(body);return this.db.transaction(async c=>{const member=(await c.query("SELECT user_id,role FROM school_memberships WHERE user_id=$1 AND school_id=$2",[userId,actor.schoolId])).rows[0];if(!member)throw new NotFoundException("Staf tidak ditemukan.");if(input.isActive===false&&member.role==='SCHOOL_ADMIN')throw new ConflictException("Akun pengelola sekolah tidak dapat dinonaktifkan dari halaman ini.");if(input.isActive!==undefined)await c.query("UPDATE school_memberships SET is_active=$3,deactivated_at=CASE WHEN $3 THEN NULL ELSE now() END WHERE user_id=$1 AND school_id=$2",[userId,actor.schoolId,input.isActive]);if(input.password)await c.query("UPDATE users SET password_hash=$2,updated_at=now() WHERE id=$1",[userId,await this.auth.hashPassword(input.password)]);await this.audit.record({schoolId:actor.schoolId,actorUserId:actor.userId,action:"staff.updated",entityType:"user",entityId:userId,metadata:{isActive:input.isActive,passwordReset:Boolean(input.password)}},c);return {ok:true};},actor.schoolId); }
  @Post("class-periods/:classPeriodId/homeroom") async assign(@Req() request:FastifyRequest,@Param("classPeriodId") classPeriodId:string,@Body() body:unknown) { const actor=this.auth.require(request,["SCHOOL_ADMIN"]);const input=assignmentSchema.parse(body);return this.db.transaction(async c=>{const period=(await c.query("SELECT id FROM class_periods WHERE id=$1",[classPeriodId])).rows[0];if(!period)throw new NotFoundException("Kelas tidak ditemukan.");const teacher=(await c.query("SELECT 1 FROM school_memberships WHERE user_id=$1 AND school_id=$2 AND role='TEACHER' AND is_active",[input.teacherUserId,actor.schoolId])).rowCount;if(!teacher)throw new NotFoundException("Akun guru aktif tidak ditemukan.");await c.query("DELETE FROM teacher_class_assignments WHERE class_period_id=$1",[classPeriodId]);const assignment=(await c.query("INSERT INTO teacher_class_assignments(school_id,class_period_id,teacher_user_id) VALUES($1,$2,$3) RETURNING *",[actor.schoolId,classPeriodId,input.teacherUserId])).rows[0];await this.audit.record({schoolId:actor.schoolId,actorUserId:actor.userId,action:"homeroom_teacher.assigned",entityType:"class_period",entityId:classPeriodId,metadata:{teacherUserId:input.teacherUserId}},c);return assignment;},actor.schoolId); }
}
