CREATE TYPE report_status AS ENUM ('DRAFT','SUBMITTED','IN_REVIEW','REVISION_REQUIRED','APPROVED','PUBLISHED');
CREATE TABLE reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, student_id uuid NOT NULL REFERENCES students(id) ON DELETE CASCADE, semester_id uuid NOT NULL REFERENCES semesters(id) ON DELETE CASCADE, status report_status NOT NULL DEFAULT 'DRAFT', submitted_at timestamptz, approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(student_id,semester_id));
CREATE TABLE report_narratives (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE, development_area_id uuid NOT NULL REFERENCES development_areas(id), content text NOT NULL, updated_by uuid NOT NULL REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(report_id,development_area_id));
CREATE TABLE report_approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE, report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE, actor_user_id uuid NOT NULL REFERENCES users(id), action varchar(40) NOT NULL, note text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX idx_reports_progress ON reports(school_id,semester_id,status);
ALTER TABLE reports ENABLE ROW LEVEL SECURITY; ALTER TABLE reports FORCE ROW LEVEL SECURITY; CREATE POLICY reports_isolation ON reports USING (school_id = NULLIF(current_setting('app.school_id',true),'')::uuid) WITH CHECK (school_id = NULLIF(current_setting('app.school_id',true),'')::uuid);
ALTER TABLE report_narratives ENABLE ROW LEVEL SECURITY; ALTER TABLE report_narratives FORCE ROW LEVEL SECURITY; CREATE POLICY report_narratives_isolation ON report_narratives USING (school_id = NULLIF(current_setting('app.school_id',true),'')::uuid) WITH CHECK (school_id = NULLIF(current_setting('app.school_id',true),'')::uuid);
ALTER TABLE report_approvals ENABLE ROW LEVEL SECURITY; ALTER TABLE report_approvals FORCE ROW LEVEL SECURITY; CREATE POLICY report_approvals_isolation ON report_approvals USING (school_id = NULLIF(current_setting('app.school_id',true),'')::uuid) WITH CHECK (school_id = NULLIF(current_setting('app.school_id',true),'')::uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON reports, report_narratives, report_approvals TO ramu_app;
