"use client";
import { FormEvent, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, UserRound } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { api } from "@/lib/api";
type Staff={id:string;name:string;email:string;role:"TEACHER"|"PRINCIPAL"|"SCHOOL_ADMIN";is_active:boolean};
export function StaffPage(){const qc=useQueryClient();const[error,setError]=useState("");const staff=useQuery({queryKey:["staff"],queryFn:()=>api<Staff[]>("/staff")});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setError("");try{await api("/staff",{method:"POST",body:JSON.stringify({name:d.get("name"),email:d.get("email"),role:d.get("role"),password:d.get("password")})});form.reset();await qc.invalidateQueries({queryKey:["staff"]})}catch(reason){setError(reason instanceof Error?reason.message:"Akun staf tidak dapat dibuat.")}}async function toggle(person:Staff){try{await api(`/staff/${person.id}`,{method:"PATCH",body:JSON.stringify({isActive:!person.is_active})});await qc.invalidateQueries({queryKey:["staff"]})}catch(reason){setError(reason instanceof Error?reason.message:"Status akun tidak dapat diubah.")}}return <><PageHeader eyebrow="Pengaturan sekolah" title="Staf sekolah" description="Buat akun guru dan kepala sekolah. Hanya wali kelas yang dapat mengelola rapor kelasnya."/>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><h2 className="font-bold">Tambah staf</h2><form onSubmit={submit} className="mt-4 space-y-3"><input required name="name" placeholder="Nama lengkap" className="w-full rounded-xl border p-3 text-sm"/><input required name="email" type="email" placeholder="email@sekolah.id" className="w-full rounded-xl border p-3 text-sm"/><select required name="role" className="w-full rounded-xl border p-3 text-sm"><option value="TEACHER">Guru</option><option value="PRINCIPAL">Kepala sekolah</option></select><input required minLength={8} name="password" type="password" placeholder="Kata sandi awal (minimal 8 karakter)" className="w-full rounded-xl border p-3 text-sm"/><Button className="w-full"><Plus size={16}/>Buat akun staf</Button></form></Card><Card><div className="flex items-center gap-2"><UserRound size={19} className="text-brand-700"/><h2 className="font-bold">Daftar staf</h2></div><div className="mt-4 space-y-2">{staff.data?.map(person=><div key={person.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 text-sm"><div><b>{person.name}</b><p className="text-slate-500">{person.email} · {person.role==="TEACHER"?"Guru":person.role==="PRINCIPAL"?"Kepala sekolah":"Admin sekolah"}</p></div>{person.role!=="SCHOOL_ADMIN"&&<Button variant="secondary" onClick={()=>void toggle(person)}>{person.is_active?"Nonaktifkan":"Aktifkan"}</Button>}</div>)}</div></Card></div></>}
