import { Body, Controller, Get, Param, Post, Query, Req } from "@nestjs/common";
import type { FastifyRequest } from "fastify";
import { z } from "zod";
import { AuditService } from "../audit/audit.service";
import { AuthService } from "../auth/auth.service";
import { DatabaseService } from "../database/database.service";
const studentSchema=z.object({name:z.string().min(2).max(120),studentNumber:z.string().max(50).optional(),classId:z.string().uuid().optional(),birthDate:z.string().date().optional(),gender:z.enum(["MALE","FEMALE"]).optional()});
const guardianSchema=z.object({name:z.string().min(2).max(120),relationship:z.string().min(2).max(50),phone:z.string().min(8).max(30),isPrimary:z.boolean().default(false)});
@Controller("students")
export class StudentsController {
 constructor(private readonly auth:AuthService,private readonly db:DatabaseService,private readonly audit:AuditService){}
 @Get() list(@Req() request:FastifyRequest,@Query("page") page="1",@Query("limit") limit="20"){const a=this.auth.require(request);const offset=(Math.max(Number(page),1)-1)*Math.min(Number(limit),100);return this.db.transaction(async c=>{const items=await c.query("SELECT s.*,c.name AS class_name FROM students s LEFT JOIN classes c ON c.id=s.class_id ORDER BY s.created_at DESC LIMIT $1 OFFSET $2",[Math.min(Number(limit),100),offset]);const total=await c.query("SELECT count(*)::int AS total FROM students");return {items:items.rows,total:total.rows[0].total,page:Number(page)};},a.schoolId)}
 @Post() async create(@Req() request:FastifyRequest,@Body() body:unknown){const a=this.auth.require(request,["SCHOOL_ADMIN"]);const input=studentSchema.parse(body);return this.db.transaction(async c=>{const r=await c.query("INSERT INTO students (school_id,name,student_number,class_id,birth_date,gender) SELECT $1,$2,$3,$4,$5,$6 WHERE $4::uuid IS NULL OR EXISTS (SELECT 1 FROM classes WHERE id=$4) RETURNING *",[a.schoolId,input.name,input.studentNumber??null,input.classId??null,input.birthDate??null,input.gender??null]);if(!r.rowCount)throw new Error("Kelas tidak ditemukan");await this.audit.record({schoolId:a.schoolId,actorUserId:a.userId,action:"student.created",entityType:"student",entityId:r.rows[0].id},c);return r.rows[0]},a.schoolId)}
 @Get(":id") detail(@Req() request:FastifyRequest,@Param("id") id:string){const a=this.auth.require(request);return this.db.transaction(async c=>{const student=(await c.query("SELECT * FROM students WHERE id=$1",[id])).rows[0];if(!student)return null;const guardians=(await c.query("SELECT * FROM guardian_contacts WHERE student_id=$1 ORDER BY is_primary DESC,name",[id])).rows;return {...student,guardians}},a.schoolId)}
 @Post(":id/guardians") async guardian(@Req() request:FastifyRequest,@Param("id") id:string,@Body() body:unknown){const a=this.auth.require(request,["SCHOOL_ADMIN"]);const input=guardianSchema.parse(body);return this.db.transaction(async c=>{const exists=await c.query("SELECT id FROM students WHERE id=$1",[id]);if(!exists.rowCount)throw new Error("Siswa tidak ditemukan");if(input.isPrimary)await c.query("UPDATE guardian_contacts SET is_primary=false WHERE student_id=$1",[id]);const r=await c.query("INSERT INTO guardian_contacts (school_id,student_id,name,relationship,phone,is_primary) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *",[a.schoolId,id,input.name,input.relationship,input.phone,input.isPrimary]);await this.audit.record({schoolId:a.schoolId,actorUserId:a.userId,action:"guardian.created",entityType:"guardian_contact",entityId:r.rows[0].id},c);return r.rows[0]},a.schoolId)}
}
